import {IRubric} from './rubric.class';
import {DEFAULT_COLOR} from '@shared/constants/constants';

export const AssignmentSettingsVersion = 1;

/**
 * An enum defining the format in which an assignment is in.
 * Assignments can be imported, shared, and exported for marking.
 * This enum defines these formats as they are written to file.
 */
export enum DistributionFormat {

  /**
   * An assignment in the source format.
   */
  DISTRIBUTED = 'DISTRIBUTED',


  /**
   * An assignment that is only used by a single user.
   * This is also the default if nothing is set
   */
  STANDALONE = 'STANDALONE'

}

/**
 * A reference to a marker if a submission is allocated
 */
export interface MakerReference {
  /**
   * Unique UUID of the maker as generated by the source assignment
   */
  id?: string;

  /**
   * Email address of the marker
   */
  email?: string;
}

/**
 * A interface defining a submission that has been allocated to a marker
 */
export interface SubmissionAllocation {
  /**
   * Name of the submission directory
   */
  submission: string;

  /**
   * Reference to the marker for the submission
   */
  marker: MakerReference;
}


export enum SubmissionState {
  /**
   * New untouched submission
   * text: "--"
   */
  NEW = 'NEW',

  /**
   * Allocated to a marker
   * text: "Assigned"
   */
  ASSIGNED_TO_MARKER = 'ASSIGNED_TO_MARKER',

  /**
   * A marked submission
   * text: "Marked"
   */
  MARKED = 'MARKED',
}

export interface Submission {
  studentName: string;
  studentSurname: string;
  studentId: string;
  allocation: MakerReference;
  directoryName: string;
  mark: number | null;
  state: SubmissionState;
  /**
   * Status for this submission as received from the LMS (grades.csv)
   */
  lmsStatusText?: string;
}

export interface AssignmentSettingsInfo {

  /**
   * Version of the settings assignment settings file
   */
  version?: number;

  /**
   * Name of the assignment
   */
  assignmentName: string;

  /**
   * Original owner of the assignment import.
   */
  owner?: MakerReference;

  /**
   * Format of the assignment directory
   */
  distributionFormat?: DistributionFormat;

  /**
   * Submissions part of this assignment.
   */
  submissions: Submission[];

  /**
   * Default color to use while marking
   */
  defaultColour?: string;

  /**
   * Copy of the actual rubric applied to this assignment
   */
  rubric?: IRubric;

  /**
   * true if from a lms, imported via import zip, false if created by upload pdf
   */
  isCreated?: boolean;

  /**
   * Date when this assignment was finalized
   */
  dateFinalized?: string;
}

export const DEFAULT_ASSIGNMENT_SETTINGS: AssignmentSettingsInfo = {
  assignmentName: null,
  version: AssignmentSettingsVersion,
  distributionFormat: DistributionFormat.STANDALONE,
  owner: null,
  dateFinalized: null,
  defaultColour: DEFAULT_COLOR,
  rubric: null,
  isCreated: false,
  submissions: []
};


